// <auto-generated />
using System;
using HibaVonal_03.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HibaVonal_03.Migrations
{
    [DbContext(typeof(HibaVonalDbContext))]
    partial class HibaVonalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HibaVonal_03.Entities.Appliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PremiseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PremiseId");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Fault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplianceId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedMaintenanceId")
                        .HasColumnType("int");

                    b.Property<int>("CollegiateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PremiseId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplianceId");

                    b.HasIndex("AssignedMaintenanceId");

                    b.HasIndex("CollegiateId");

                    b.HasIndex("PremiseId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Faults");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CollegiateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegiateId");

                    b.HasIndex("FaultId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.MaintainerSpecialisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaintainerSpecialisations");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Premise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("NameOrNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Premises");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.ToolOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FaultId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FaultId");

                    b.ToTable("ToolOrders");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<int>("Role").HasValue(2);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MaintainerMaintainerSpecialisation", b =>
                {
                    b.Property<int>("MaintainersId")
                        .HasColumnType("int");

                    b.Property<int>("MaintenanceSpecialisationId")
                        .HasColumnType("int");

                    b.HasKey("MaintainersId", "MaintenanceSpecialisationId");

                    b.HasIndex("MaintenanceSpecialisationId");

                    b.ToTable("MaintainerSpecialisationAssignments", (string)null);
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Collegiate", b =>
                {
                    b.HasBaseType("HibaVonal_03.Entities.User");

                    b.Property<int>("DormRoomId")
                        .HasColumnType("int");

                    b.HasIndex("DormRoomId");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Maintainer", b =>
                {
                    b.HasBaseType("HibaVonal_03.Entities.User");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Appliance", b =>
                {
                    b.HasOne("HibaVonal_03.Entities.Premise", "Premise")
                        .WithMany("Appliances")
                        .HasForeignKey("PremiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premise");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Fault", b =>
                {
                    b.HasOne("HibaVonal_03.Entities.Appliance", "Appliance")
                        .WithMany("Faults")
                        .HasForeignKey("ApplianceId");

                    b.HasOne("HibaVonal_03.Entities.Maintainer", "AssignedMaintenance")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("AssignedMaintenanceId");

                    b.HasOne("HibaVonal_03.Entities.Collegiate", "Collegiate")
                        .WithMany("ReportedFaults")
                        .HasForeignKey("CollegiateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HibaVonal_03.Entities.Premise", "Premise")
                        .WithMany("OccurredFaults")
                        .HasForeignKey("PremiseId")
                        .IsRequired();

                    b.HasOne("HibaVonal_03.Entities.MaintainerSpecialisation", "Specialization")
                        .WithMany("AssignedFaults")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appliance");

                    b.Navigation("AssignedMaintenance");

                    b.Navigation("Collegiate");

                    b.Navigation("Premise");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Feedback", b =>
                {
                    b.HasOne("HibaVonal_03.Entities.Collegiate", "Collegiate")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CollegiateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HibaVonal_03.Entities.Fault", "Fault")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collegiate");

                    b.Navigation("Fault");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.ToolOrder", b =>
                {
                    b.HasOne("HibaVonal_03.Entities.Fault", "Fault")
                        .WithMany("ToolOrders")
                        .HasForeignKey("FaultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fault");
                });

            modelBuilder.Entity("MaintainerMaintainerSpecialisation", b =>
                {
                    b.HasOne("HibaVonal_03.Entities.Maintainer", null)
                        .WithMany()
                        .HasForeignKey("MaintainersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HibaVonal_03.Entities.MaintainerSpecialisation", null)
                        .WithMany()
                        .HasForeignKey("MaintenanceSpecialisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Collegiate", b =>
                {
                    b.HasOne("HibaVonal_03.Entities.Premise", "DormRoom")
                        .WithMany("Residents")
                        .HasForeignKey("DormRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DormRoom");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Appliance", b =>
                {
                    b.Navigation("Faults");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Fault", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ToolOrders");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.MaintainerSpecialisation", b =>
                {
                    b.Navigation("AssignedFaults");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Premise", b =>
                {
                    b.Navigation("Appliances");

                    b.Navigation("OccurredFaults");

                    b.Navigation("Residents");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Collegiate", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ReportedFaults");
                });

            modelBuilder.Entity("HibaVonal_03.Entities.Maintainer", b =>
                {
                    b.Navigation("AssignedFaults");
                });
#pragma warning restore 612, 618
        }
    }
}
